//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP_WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public long ID { get; set; }
        public long CusID { get; set; }
        public long WorkTypeID { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public long JobStatusID { get; set; }
        public long CoordinatorID { get; set; }
        public long SupplierID { get; set; }
        public System.DateTime CompletedDate { get; set; }
        public long FinanceID { get; set; }
        public string CompletedBy { get; set; }
        public long ProductID { get; set; }
    
        public virtual Finance Finance { get; set; }
        public virtual Market_Participant Market_Participant { get; set; }
        public virtual Product Product { get; set; }
        public virtual WorkType WorkType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual JobStatu JobStatu { get; set; }
    }
}
