//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP_WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Power_Consumption
    {
        public long ID { get; set; }
        public long CustID { get; set; }
        public Nullable<long> Usage { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
