//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP_WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public long ID { get; set; }
        public string House { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string State { get; set; }
        public long Pin { get; set; }
        public long UserID { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
